resources:
# The "name" property below will be the name of the new project
- name: dm-proj-test-jbowen16
  type: turbo-dev/composite:project-test25
  properties:
    region: us-central
    # Change this to your organization ID.
    organization-id: "433637338589"
    # Change the following to your organization's billing account
    billing-account-name: billingAccounts/00A5B6-123E67-6EEAD6
    # The apis to enable in the new project.
    # To see the possible APIs, use gcloud CLI: gcloud service-management list
    apis:
    - deploymentmanager.googleapis.com
    - logging.googleapis.com
    - appengine.googleapis.com
    # The service accounts you want to create in the project

    labels:
    - key1: val1,
    - key2: val2,
    
    service-accounts:
    - my-service-account-1
    # IAM policy on the new project
    iam-policy:
      bindings:
      - role: roles/owner
        members:
        # Make sure to include the DM service account that is doing the deployment!
        - serviceAccount:438049019500@cloudservices.gserviceaccount.com
        - user:bowenjosh@google.com
        # Add any others you want to have access
      # - role: roles/viewer
        # members:

